# Generated by Django 4.1.4 on 2024-03-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping_pong', '0004_auto_20240307_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friends',
        ),
    ]
