# Generated by Django 4.1.4 on 2024-03-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping_pong', '0006_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
