# PostgreSQL'in resmi Docker görüntüsünü kullanın
FROM postgres:13

# Veritabanını çalıştırmak için gerekli ortam değişkenlerini ayarlayın
ENV POSTGRES_DB=transcendence
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=p123@sqd

# PostgreSQL'in varsayılan portunu expose etmeniz gerekmez, çünkü Compose dosyanızda port yönlendirmesi yapıyorsunuz.
