# Generated by Django 4.1.4 on 2024-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_pong', '0009_user_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='normal_avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='intra_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
