# Generated by Django 4.1.4 on 2024-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping_pong', '0012_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languagePreference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
